### ISSUE TITLE
想知道48的这个pa码的生成规则和检验规则是啥呀

### ISSUE THREAD

**Issue by KkEeVvIiNnn** [wdwind/pocket48_api#3]

**Comment by wdwind** [comment]
生成规则很简单：
```python
r = str(uuid.uuid4()).replace('-', '')
t = int(time.time()) * 1000
salt = '?'
s = '{}{}{}'.format(t, r, salt).encode('utf-8')
m = hashlib.md5(s).hexdigest()
pa = b64encode('{},{},{}'.format(t, r, m).encode('utf-8'))
```
问题关键在于 `salt` 是nativelib生成的，这个我水平有限，暂时还没搞清楚。

**Comment by GNZ48live** [comment]
> 生成规则很简单：
> 
> ```python
> r = str(uuid.uuid4()).replace('-', '')
> t = int(time.time()) * 1000
> m = md5(r, t)
> pa = b64encode('{},{},{}'.format(t, r, m).encode('utf-8'))
> ```
> 
> 问题关键在于 `md5` 是一个native method，这个我水平有限，暂时还没搞清楚。

看来之前也是找对了，但按规则生成的pa就是500。应该是也卡在md5这了。TmT。
